version: "3.7"

services:
  ipfs:
    image: ceramicnetwork/go-ipfs-daemon:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - "./data/ipfs:/data/ipfs"
    ports:
      - "5001:5001"
      - "8011:8011"
      
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
      - ./psql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  
  ceramic:
    image: ceramicnetwork/js-ceramic:latest
    environment:
      - NODE_ENV=production
      - CERAMIC_INDEXING_DB_URI=postgres://postgres:postgres@postgres:5432/ceramic
    restart: always
    volumes:
      - "./ceramic/config.json:/root/.ceramic/daemon.config.json"
      - "./data/ceramic/logs:/root/.ceramic/logs"
      - "./data/ceramic/statestore:/root/.ceramic/statestore"
    ports:
      - "7007:7007"
    depends_on:
      - postgres
      - ipfs
